implement components for restaurants page
IvanKrasnikov/react-2023-11-09 pull request #2
Opened 2023-11-19 22:50 UTC by IvanKrasnikov

2023-11-20 17:07 UTC, SArchieEdu requested changes
Нужно доделать

2023-11-20 17:07 UTC, SArchieEdu commented on src/components/restaurant/Restaurant.jsx
> +        </div>
Нужно разбить на компоненты

2023-11-22 18:28 UTC, IvanKrasnikov commented on src/components/restaurant/Restaurant.jsx
> +        </div>
done

2023-11-23 11:49 UTC, SArchieEdu approved these changes

2023-11-23 11:55 UTC, merged