temp PR into branch lecture-2/hw Lecture 3/hw
IvanKrasnikov/react-2023-11-09 pull request #3
Opened 2023-11-23 00:10 UTC by IvanKrasnikov

2023-11-23 12:21 UTC, SArchieEdu requested changes

2023-11-23 12:21 UTC, SArchieEdu commented on src/pages/restaurants-page/RestaurantsPage.jsx
> +    const selectedRestaurants = restaurants.filter((restaurant) => {
нам нужен только 1 ресторан. find

2023-11-23 12:21 UTC, SArchieEdu commented on src/components/dish/Dish.jsx
> +    /* TODO: remove logs after answering questions */
а в чем вопрос?

2023-11-23 12:32 UTC, IvanKrasnikov commented on src/components/dish/Dish.jsx
> +    /* TODO: remove logs after answering questions */
Думал на лекции спросить. Написал в дискорде в лс

2023-11-23 17:03 UTC, IvanKrasnikov commented on src/pages/restaurants-page/RestaurantsPage.jsx
> +    const selectedRestaurants = restaurants.filter((restaurant) => {
Поправил, Компонент Restaurants пока не стал удалять

2023-11-30 13:53 UTC, ArchieSA approved these changes

2023-11-30 13:56 UTC, merged